version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=Cherry@07
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Cherry@07
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
        PGADMIN_DEFAULT_PASSWORD: Cherry@07
        PGADMIN_DEFAULT_EMAIL: kr7168799@gmail.com