---
- name: Setup mail server
  hosts: debian_servers
  become: yes
  tasks:
    - name: Pull Docker mailserver image
      docker_image:
        name: villain1039532/mailserver:latest
        source: pull

    - name: Run Docker mailserver container
      docker_container:
        name: mailserver
        image: villain1039532/mailserver:latest
        state: started
        recreate: yes
        ports:
          - "25:25"
          - "143:143"
          - "110:110"
        volumes:
          - "/data/mailserver:/data/mailserver"
          - "/etc/letsencrypt/live/seventwelve.in:/etc/letsencrypt/live/seventwelve.in"




        
