---
- name: Deploy Next.js application 
  hosts: debian_servers
  become: yes
  tasks:
    - name: Check if the Docker container is present
      shell: docker inspect -f '{{ .State.Running }}' villain1039532/netjs:latest
      register: container_status
      ignore_errors: yes

    - name: Stop the Docker container if running
      docker_container:
        name: villain1039532/netjs:latest
        state: stopped
      when: container_status.stdout == "true"
      register: stopped_container
      ignore_errors: yes

    - name: Pull Docker image
      docker_image:
        name: villain1039532/netjs:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: netjs
        image: villain1039532/netjs:latest
        state: started
        ports:
          - "3000:3000"
        volumes:
          - "/data"
  #   - name: Configure Nginx
  #     template:
  #       src: nginx.conf.j2
  #       dest: /etc/nginx/sites-available/nextjs_app
  #     notify:
  #       - Reload Nginx

  #   - name: Enable Nginx site
  #     file:
  #       src: /etc/nginx/sites-available/nextjs_app
  #       dest: /etc/nginx/sites-enabled/nextjs_app
  #       state: link
  #     notify:
  #       - Reload Nginx

  # handlers:
  #   - name: Reload Nginx
  #     service:
  #       name: nginx
  #       state: reloaded
