---
- name: Deploy Next.js application 
  hosts: debian_servers
  become: yes
  tasks:

    - name: Stop a container
      docker_container:
        name: netjs
        state: stopped
        
    - name: Remove Docker image
      docker_image:
        name: your_image_name
        state: absent
        force: yes

    - name: Pull Docker image
      docker_image:
        name: villain1039532/netjs:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: netjs
        image: villain1039532/netjs:latest
        state: started
        recreate: yes
        ports:
          - "3000:3000"
        volumes:
          - "/data"
  #   - name: Configure Nginx
  #     template:
  #       src: nginx.conf.j2
  #       dest: /etc/nginx/sites-available/nextjs_app
  #     notify:
  #       - Reload Nginx

  #   - name: Enable Nginx site
  #     file:
  #       src: /etc/nginx/sites-available/nextjs_app
  #       dest: /etc/nginx/sites-enabled/nextjs_app
  #       state: link
  #     notify:
  #       - Reload Nginx

  # handlers:
  #   - name: Reload Nginx
  #     service:
  #       name: nginx
  #       state: reloaded
